### ISSUE TITLE
support corporate ca for SourceController

### ISSUE THREAD

**Issue by poblin-orange** [fluxcd-community/helm-charts#119]
### Is your feature request related to a problem ?

Unable to use flux helm chart out of the box when targeting a corporate GitRepository (corporate ca for tls access)
Same for notification controller when targeting corporate mattermost

### Describe the solution you'd like.

Id like to be able to set wether;
- corporate ca to use for source controller
- volumes/volumes mount for source controller

### Describe alternatives you've considered.

Currently using a Kyverno policy to set the additional volume / volumeount for our corporate ca.
This is quite specific to our environement and requires kyverno before installing flux helm chart ....

**Comment by haarchri** [comment]
Can you Check:

https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/templates/source-controller.yaml#L99

https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/templates/source-controller.yaml#L114

**Comment by poblin-orange** [comment]
@haarchri not sure its enough.
Typically, custom ca cert are loaded from well know location /etc/ssl/cert
see below the kyverno patch we use
```
apiVersion: kyverno.io/v1
kind: Policy
metadata:
name: kyverno-fluxcd-add-ca-cert-deployments
namespace: flux-system
spec:
background: false
rules:
- name: add-ca-cert-pod-volume
  match:
	resources:
	  kinds:
	  - Deployment
	  names:
	  - "source-controller" #only source controller requires ca cert and/or internet proxy
  mutate:
	#this will be merged
	patchStrategicMerge:
	  spec:
		template:
		  spec:
			containers:
			- name: manager
			  #for corporate ca
			  volumeMounts:
			  - name: cert-volume
				mountPath: /etc/ssl/certs
			volumes:
			- name: cert-volume
			  hostPath:
				path: /etc/ssl/certs
				type: Directory
```
