### ISSUE TITLE
flux-sync .gitRepository.spec.ignore multiline support

### ISSUE THREAD

**Issue by odise** [fluxcd-community/helm-charts#133]
### Describe the bug a clear and concise description of what the bug is.

I'm struggling setting a multiline git ignore configuration like:

```yaml
gitRepository:
  spec:
    url: repository_url
    ref: {"branch": "branch"}
    ignore: |
      # exclude all
      /*
      # include deploy dir
      !/cluster-name/fluxcd-applications
```

This results in:

```
Error: YAML parse error on flux2-sync/templates/flux-gitrepository.yaml: error converting YAML to JSON: yaml: line 20: could not find expected ':'
```

### What's your helm version?

3.9.4

### What's your kubectl version?

v1.24.3

### What's the chart version?

1.0.0

### Enter the changed values of values.yaml?

gitRepository:
  spec:
    ignore: |
      # exclude all
      /*
      # include deploy dir
      !/cluster-name/fluxcd-applications

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -n flux-system -f x fluxcd-apps fluxcd-community/flux2-sync

**Comment by odise** [comment]
I guess something like:
```
ignore: {{ .Values.gitRepository.spec.ignore | toYaml }}
```
in https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2-sync/templates/flux-gitrepository.yaml#L32 should fix the problem.

**Comment by stefanprodan** [comment]
this has nothing to do with ignore, multi-line works file, the ref is wrong.

**Comment by odise** [comment]
Even when I set it to:

```yaml
gitRepository:
  spec:
    url: repository_url
    ref: 
      branch:  branch
```

the error stays the same.
