### ISSUE TITLE
Included `extraObjects` example in `flux2/values.yaml` doesn't appear to work.

### ISSUE THREAD

**Issue by thebearingedge** [fluxcd-community/helm-charts#183]
### Describe the bug a clear and concise description of what the bug is.

`extraObjects` cannot refer to Flux CRDs as shown in the example `flux2/values.yaml` file.

### What's your helm version?

v3.12.3

### What's your kubectl version?

v1.28.1

### What's the chart version?

2.9.2

### What happened?

I received an error when trying to set up a `Bucket` and a `Kustomization` when installing `flux2` via Helm.

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "source" namespace: "flux-system" from "": no matches for kind "Bucket" in version "source.toolkit.fluxcd.io/v1beta2"
ensure CRDs are installed first, resource mapping not found for name: "source" namespace: "flux-system" from "": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1"
ensure CRDs are installed first]
```

### What you expected to happen?

Either the `extraObjects` are successfully installed _after_ flux CRDs or there's no flux CRDs in the example `values.yaml`, if it's not technically possible.

### How to reproduce it?

Include `extraObjects` in custom `values.yaml` that refer to Flux CRDs.

### Enter the changed values of values.yaml?

```yaml
imageAutomationController:
  create: false
imageReflectionController:
  create: false
sourceController:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
helmController:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
kustomizeController:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
notificationController:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
extraObjects:
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: Bucket
    metadata:
      name: source
      namespace: flux-system
    spec:
      interval: 1m
      provider: generic
      bucketName: source
      endpoint: minio.flux-system.svc.cluster.local:9000
      insecure: true
      secretRef:
        name: bucket-credentials
  - apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: source
      namespace: flux-system
    spec:
      interval: 1m
      sourceRef:
        kind: Bucket
        name: source
      path: ./environments/local
      prune: true
      timeout: 1m
```

### Enter the command that you execute and failing/misfunctioning.

```shell
helm install \
    --version 2.9.2 \
    --namespace flux-system \
    --repo https://fluxcd-community.github.io/helm-charts \
    --values cluster/flux2-values.yaml \
    flux2 flux2
```

### Anything else we need to know?

I'll spend some time checking if this is a limitation in Helm, I'm not familiar with authoring charts.

Thank you!

**Comment by thebearingedge** [comment]
I did attempt to [add `helm.sh/hook` annotations](https://helm.sh/docs/topics/charts_hooks/) to my CRs, and it appears to work once, but the next few retries still gave the same errors.

So it may have had no effect.

**Comment by thebearingedge** [comment]
I'm going to close this. I do believe that I had some typos when trying the `helm.sh/hook` annotations. Today I've tried them again and they are working consistently. For reference, a working example bucket looks like:

```yaml
extraObjects:
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: Bucket
    metadata:
      name: local-sync
      namespace: gitops-system
      annotations:
        helm.sh/hook: post-install # omitting this annotation causes install to fail
```
