### ISSUE TITLE
Temp directory in memory

### ISSUE THREAD

**Issue by ngoeddel-openi** [fluxcd-community/helm-charts#185]
### Is your feature request related to a problem ?

With a small enough refresh interval for the source and kustomize controller they can create a lot of disk I/O on a system.
In our case it is just too much, the kustomize pod constantly uses 200% CPU and creates a lot of writes to the underlying file system.
Unfortunately there is no possibility to change the volume mount for `/tmp`. It is just a simply `emptyDir` volume.
https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/templates/kustomize-controller.yaml#L134

### Describe the solution you'd like.

My solution would be to add additional parameters for `emptyDir` or somehow using `.Values.kustomizeController.volumes` to override the `temp` volume.

The first idea would be the easiest one I guess:
```yaml
      ...
      volumes:
      - name: temp
        emptyDir:
          {{ .Values.kustomizeController.tempOptions | toYaml | nindent 10 }}
      ...
```
Then there should be a default for that in `values.yaml`:
```yaml
kustomizeController:
  tempOptions: {}
```
Which can be overridden like this:
```yaml
kustomizeController:
  tempOptions:
    medium: Memory
    sizeLimit: 128Mi
```

### Describe alternatives you've considered.

NONE
