### ISSUE TITLE
lables for most of the deployments not working

### ISSUE THREAD

**Issue by haarchri** [fluxcd-community/helm-charts#19]
### Describe the bug a clear and concise description of what the bug is.

lables for most of the deployments not working

### What's your helm version?

version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/arm64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### What's the chart version?

0.4.0

### What happened?

```
    message: 'create failed: failed to install release: YAML parse error on flux2/templates/kustomize-controller.yaml:
      error converting YAML to JSON: yaml: line 20: mapping values are not allowed
```

### What you expected to happen?

working labels

### How to reproduce it?

```
      sourcecontroller:
        labels:
          crossplane.io/claim-name: test
          crossplane.io/claim-namespace: test
          crossplane.io/composite: test
```

### Enter the changed values of values.yaml?

```
      sourcecontroller:
        labels:
          crossplane.io/claim-name: test
          crossplane.io/claim-namespace: test
          crossplane.io/composite: test
```

### Enter the command that you execute and failing/misfunctioning.

crossplane composition rollout
