### ISSUE TITLE
Ability to set name for gitrepository and kustomization

### ISSUE THREAD

**Issue by grzegorzgniadek** [fluxcd-community/helm-charts#209]
### Is your feature request related to a problem ?

Allow flux2-sync to set gitrepository and kustomization .metadata.name

### Describe the solution you'd like.

```
metadata:
  name: {{ .Values.gitRepository.name | default .Release.Name  }}
```
 in flux-gitrepository.yaml
and 
```
metadata:
  name: {{ .Values.kustomization.name | default .Release.Name  }}
sourceRef:
  kind: GitRepository
  name:  {{ .Values.gitRepository.name | default .Release.Name  }}
```
in flux-kustomization.yaml

### Describe alternatives you've considered.

None
