### ISSUE TITLE
[flux2] support containerName for deployments can be customised

### ISSUE THREAD

**Issue by lkaluza-fadi** [fluxcd-community/helm-charts#230]
### Is your feature request related to a problem ?

Currently all containerNames in a flux deployment/pods are called `manager`. As we are using datadog as a monitoring tool its hard to figure out which container has maybe some resource issues because they are all named the same.

### Describe the solution you'd like.

We would like to have the option to configure the name of the container in the `helm_release` like:
```
helmController:
  containerName: <some-containerName>
sourceController:
  containerName: <some-containerName>
etc...
```   

### Describe alternatives you've considered.

None
