### ISSUE TITLE
Please include secret.data: example

### ISSUE THREAD

**Issue by throwawayaccount0153** [fluxcd-community/helm-charts#41]
### Describe the bug a clear and concise description of what the bug is.

Please include a secret.data: {} example as I cannot get a secret to work.  This is due to the fact that It doesn't appear that data: {} accepts a multi line string which is needed to accept an ssh private key, I don't believe json accepts multiline values.  can this be changed to be more multi line string friendly?

### What's your helm version?

latest stable

### What's your kubectl version?

latest stable

### What's the chart version?

latest stable

### What happened?

json only accepts string

### What you expected to happen?

I expect to be able to paste an ssh key in as a string in the value and have it work

### How to reproduce it?

secret:
  create: true
  data: {"foo": "SSH KEY"}

### Enter the changed values of values.yaml?

secret:
  create: true
  data: {} <-- this is the problem value

### Enter the command that you execute and failing/misfunctioning.

i'm running via terraform via a helm_release resource but this is the same as the helm install command listed here

### Anything else we need to know?

no

**Comment by haarchri** [comment]
we use it like this:
in chart 

flux2:
```
              kustomizecontroller:
                secret:
                  create: true
                  name: netrc
                  data:
                    .netrc: "machine gitlab.com \nlogin git \npassword password" ## multiline via \n
                extraSecretMounts:
                  - name: netrc
                    mountPath: "/home/controller/.netrc"
                    subPath: .netrc
                    secretName: netrc
                    readOnly: true
```

in flux2-sync:

```
              secret:
                create: true
                data:
                  username: gitlab-ci-token
                  password: password
```
