### ISSUE TITLE
kustomizationlist{} results in to much kustomizations n+1

### ISSUE THREAD

**Issue by haarchri** [fluxcd-community/helm-charts#60]
### Describe the bug a clear and concise description of what the bug is.

since #55  we have issues with kustomization / kustomizationlist

values.yaml:

```
            values:
              gitRepository:
                spec:
                  url: https://github.com/xxx.git
                  ref:
                    branch: master
              kustomizationlist:
                - spec:
                    interval: 5m
                    path: ./flux2-kustomize/test
                    prune: true
                    timeout: 5m
                - spec:
                    dependsOn:
                      - path: ./flux2-kustomize/test
                    interval: 5m
                    path: ./flux2-kustomize/configuration
                    prune: true
                    timeout: 5m
```

results in: 3 kustomizations

```
flux-system   xxx                                 False   Cluster/xxx namespace not specified, error: the server could not find the requested resource (patch clusters.xxx.io xxx)...   41m

flux-system   xxx-flux2-kustomize-configuration   True    Applied revision: feature/flux2/a98f8afc6581d421c1e8e8b063a0191d4e7075d1                                                                                                                       41m

flux-system   xxx-flux2-kustomize-crossplane      True    Applied revision: feature/flux2/a98f8afc6581d421c1e8e8b063a0191d4e7075d1                                                                                                                       41m
```

side note: 
we have also issues if dependsOn Path and Release Name is more then 63 characters long: https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2-sync/templates/kustomization.yaml#L75

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### What's the chart version?

0.3.6

### Enter the command that you execute and failing/misfunctioning.

kubectl

**Comment by haarchri** [comment]
we found an solution we simply set  - thanks @dwerder 
 ```
           values:
              gitRepository:
                spec:
                  url: https://github.com/xxx.git
                  ref:
                    branch: master
              kustomization: false
              kustomizationlist:
                - spec:
                    interval: 5m
                    path: ./flux2-kustomize/test
                    prune: true
                    timeout: 5m
                - spec:
                    dependsOn:
                      - path: ./flux2-kustomize/test
                    interval: 5m
                    path: ./flux2-kustomize/configuration
                    prune: true
                    timeout: 5m
```
